name: ecoNet-OT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies: 
  - python=3.12
  - pip=23.3.1
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - jupyter
  - scikit-learn=1.3.0
  - tqdm=4.65.0
  - networkx=3.1 
  - pot=0.9.3
  - ipython=8.20.0
  - scipy=1.12.0
  - openpyxl=3.0.10
  - pygraphviz=1.9
